server:
  port: 8090
  context-path: /
spring:
  jmx:
    default-domain: blog-gem-api
  profiles:
    active: datasource,mybatis
logging:
  level:
path:
  markdown:
    root: '/home/project/node/blog_node/public/markdown'
    # 展示路径
  html: '/markdown'